# Torrent - Install
- name: Get binary path
  ansible.builtin.command: which {{ torrent_bin }}
  register: torrent_binary_path
  changed_when: false
  failed_when: false

- name: Get PPA repository key fingerprint
  ansible.builtin.uri:
    url: https://api.launchpad.net/devel/~qbittorrent-team/+archive/ubuntu/qbittorrent-stable
    return_content: true
    method: GET
    headers:
      Accept: 'application/json'
  register: torrent_repository_key_fingerprint
  when: torrent_binary_path.stdout == ''

- name: Add repository
  ansible.builtin.deb822_repository:
    name: "qbittorrent-stable-{{ ansible_facts['distribution_release'] }}"
    types: deb
    uris: https://ppa.launchpadcontent.net/qbittorrent-team/qbittorrent-stable/ubuntu
    suites: "{{ ansible_facts['distribution_release'] }}"
    components: main
    signed_by: |
      {{ lookup('ansible.builtin.url',
      'https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x' + torrent_repository_key_fingerprint.json.signing_key_fingerprint,
      split_lines=False) }}
  when: torrent_binary_path.stdout == ''

- name: Install qBittorrent
  ansible.builtin.apt:
    name: qbittorrent-nox
    state: present
  when: torrent_binary_path.stdout == ''

- name: Create user
  ansible.builtin.user:
    name: '{{ torrent_user }}'
    shell: /usr/sbin/nologin
    create_home: false
    home: '{{ torrent_folder }}'
    system: true
    password_lock: true

- name: Create folders
  ansible.builtin.file:
    path: '{{ item }}'
    state: directory
    mode: '755'
    owner: '{{ torrent_user }}'
    group: '{{ torrent_user }}'
  loop:
    - '{{ torrent_folder }}'
    - '{{ torrent_config_file_folder }}'

- name: Create systemd service
  ansible.builtin.template:
    src: '{{ item }}.j2'
    dest: '/lib/systemd/system/{{ item }}'
    owner: '{{ base_user }}'
    group: '{{ base_group }}'
    mode: '644'
  loop:
    - '{{ torrent_service_name }}.service'
  notify:
    - 'Restart service {{ torrent_service_name }}'

- name: Configure app
  ansible.builtin.include_tasks:
    file: configure.yml

- name: Enable and start service
  ansible.builtin.systemd_service:
    enabled: true
    state: started
    name: '{{ torrent_service_name }}'

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
