# Common
- name: Create base folder
  ansible.builtin.file:
    path: '{{ base_folder }}'
    state: directory
    mode: '755'
    owner: '{{ base_user }}'
    group: '{{ base_group }}'

- name: Create temp folder
  ansible.builtin.file:
    path: '{{ temp_folder }}'
    state: directory
    mode: '777'
    owner: '{{ base_user }}'
    group: '{{ base_group }}'
  when: temp_folder is not exists

- name: Update cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 86400

- name: Install dependencies
  ansible.builtin.apt:
    name: acl
    state: present

- name: Check apt
  ansible.builtin.command: apt install -y
  register: common_apt_status
  changed_when: false
  ignore_errors: true

- name: Fix interrupted packages installation
  ansible.builtin.command: dpkg --configure -a
  changed_when: false
  failed_when: false
  when: common_apt_status.stderr is search('dpkg --configure')

- name: Get Public IP
  ansible.builtin.include_tasks:
    file: public_ip.yml

- name: Setup firewall
  ansible.builtin.include_tasks:
    file: firewall.yml
