# Watcher - Variables
---
watcher_aws_cli_url:      "https://awscli.amazonaws.com/awscli-exe-linux-{{ ansible_facts['architecture'] if ansible_facts['architecture'] == 'x86_64' else 'aarch64' }}.zip" # noqa: yaml[line-length]
watcher_aws_cli_archive:  awscliv2.zip
watcher_desired_capacity: ''
