name: Ansible


on:
  push:
    branches:
      - main
    paths: &paths
      - ansible/**
      - '!**.md'
      - .github/workflows/ansible.yml
  pull_request:
    paths: *paths
  workflow_dispatch:


env:
  ansible-directory: ansible


concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true


jobs:
  ansible-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Run ansible-lint
        uses: ansible/ansible-lint@main
        with:
          working_directory: ${{ env.ansible-directory }}

  ansible-playbook:
    runs-on: ubuntu-latest
    needs: ansible-lint
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install Ansible
        run: |
          python3 -m pip install --user ansible jmespath
          ansible --version

      - name: Run ansible-playbook
        run: ansible-playbook --become ${{ env.ansible-directory }}/playbook.yml
        env:
          ANSIBLE_LOCALHOST_WARNING: false
          ANSIBLE_INVENTORY_UNPARSED_WARNING: false
          ANSIBLE_STDOUT_CALLBACK: debug
          ANSIBLE_CALLBACKS_ENABLED: profile_tasks
          ANSIBLE_VERBOSITY: ${{ runner.debug == '1' && 3 || 0 }}
          ANSIBLE_DISPLAY_TRACEBACK: ${{ runner.debug == '1' && 'always' || 'never' }}
          ANSIBLE_REMOTE_TMP: /tmp
